# Generated by Django 4.2.5 on 2024-03-16 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0004_alter_orderitem_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='amount_paid',
        ),
    ]
